# Site settings
title: "Mitchell Smith"
subtitle: "mitchellsmith.net"
email: "mitchellsletterbox@outlook.com"
baseurl: http://mitchellsmith.net/blog.html
url: http://mitchellsmith.net
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Mitchell Smith
description: "A home for my projects and musings"
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: https://github.com/RandyMustache

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.mdm", "node_modules", "gulpfile.js"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]